    disabled = false
    languageCode = "en"
    languageName = "English"
    weight = 1
    title = "Jatery Chen"

[params]
    displayName = "EN"
    isoCode = "en"
    rtl = false
    dateFormat = "2006-01-02"
    logo = "profile.jpg"

[params.author]
    name = "Jatery Chen"
    image = "profile.jpg"
    imageQuality = 96
    headline = "Why I'm writing this?"
    bio = "anxious undergraduate"
    links = [
        { github = "https://github.com/Jatery" },
        { linkedin = "www.linkedin.com/in/彥璋-陳-80a368356" },
        { x-twitter = "https://x.com/bluefatbird" },
        { youtube = "https://www.youtube.com/@bluefatbird" },
        { soundcloud = "https://soundcloud.com/bluefatbird" },
        { instagram = "https://www.instagram.com/cyz_jatery/" },
    ]
