    disabled = false
    languageCode = "zh-tw"
    languageName = "Chinese (Traditional)"
    weight = 1
    title = "Jatery's Blog"

[params]
    displayName = "ZH-TW"
    isoCode = "zh-tw"
    rtl = false
    dateFormat = "2006-01-02"
    logo = "profile.jpg"

[params.author]
    name = "Jatery Chen"
    image = "profile.jpg"
    imageQuality = 96
    headline = "一點生活記錄"
    bio = "手沾程式和音樂的資工系學生"
    links = [
        { github = "https://github.com/Jatery" },
        { instagram = "https://www.instagram.com/cyz_jatery/" },
        { threads = "https://www.threads.com/@cyz_jatery" },
        { youtube = "https://www.youtube.com/@bluefatbird" },
        { soundcloud = "https://soundcloud.com/bluefatbird" },
    ]
