    disabled = false
    languageCode = "en"
    languageName = "English"
    weight = 1
    title = "Jatery Chen"

[params]
    displayName = "ZH-TW"
    isoCode = "zh-tw"
    rtl = false
    dateFormat = "2006-01-02"
    logo = "profile.jpg"
    author = { name = "Jatery Chen", bio = "anxious undergraduate" }

[author]
    name = "Jatery Chen"
    image = "profile.jpg"
    headline = "Why I'm writing this?"
    bio = "anxious undergraduate"
