[[main]]
    name = "About"
    pageRef = "about"
    weight = 1

[[main]]
    name = "Now"
    pageRef = "now"
    weight = 2

[[main]]
    name = "Posts"
    pageRef = "posts"
    identifier = "O2yoyGnVHs"
    weight = 10

[[main]]
    name = "Tags"
    pageRef = "tags"
    weight = 20

[[footer]]
    none = "none"
