[[main]]
    name = "About"
    pageRef = "about"
    weight = 10

[[main]]
    name = "Now"
    pageRef = "now"
    weight = 20

[[main]]
    name = "Posts"
    pageRef = "/posts/"
    identifier = "O2yoyGnVHs"
    weight = 30

[[main]]
    name = "Tags"
    pageRef = "tags"
    weight = 40

[[footer]]
    none = "none"
