[[main]]
    none = "none"

[[main]]
    name = "Posts"
    pageRef = "posts"
    identifier = "O2yoyGnVHs"
    weight = 10

[[main]]
    name = "Tags"
    pageRef = "tags"
    weight = 20

[[footer]]
    none = "none"
